ID-16612: Adyen 3Ds security adaptations
tagheuerhq/adyen-salesforce-commerce-cloud pull request #6
Opened 2021-04-22 08:36 UTC by TarasBozhok

[ADYEN][SFCC] Security adaptations due to Adyen cartridge version (3DS)

2021-04-22 12:18 UTC, mchamponnois requested changes

2021-04-22 12:18 UTC, mchamponnois commented on cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
> +          ContinueURL: TermURL,
indentation issue + the comma at the end will break the process (not supported with our compatibility mode on TAG Heuer), did you test your changes ?

2021-04-22 12:18 UTC, mchamponnois commented on cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
> +    res.redirect(URLUtils.url('Home-Show', 'Payment','Failed3DS'));
eslint: always space after comma

2021-04-22 12:18 UTC, mchamponnois commented on cartridges/int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/adyen_credit.js
> +                token3ds2: result.token3ds2,
remove the comma at the end

2021-04-22 13:02 UTC, TarasBozhok commented on cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
> +          ContinueURL: TermURL,
Yes

2021-04-23 12:02 UTC, TarasBozhok commented on cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
> +          ContinueURL: TermURL,
Indentation fixed, comma removed.

2021-04-23 12:02 UTC, TarasBozhok commented on cartridges/int_adyen_SFRA/cartridge/controllers/Adyen.js
> +    res.redirect(URLUtils.url('Home-Show', 'Payment','Failed3DS'));
Space added.

2021-04-23 12:03 UTC, TarasBozhok commented on cartridges/int_adyen_SFRA/cartridge/scripts/hooks/payment/processor/adyen_credit.js
> +                token3ds2: result.token3ds2,
Comma removed.

2021-04-28 07:17 UTC, mchamponnois approved these changes

2021-04-29 08:47 UTC, merged